version: "3"

services:
  app:
    image: app
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - .:/srv/app/
    networks:
      - network-parser
    command: "poetry run python src/main.py"
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - network-parser
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gces
      MONGO_INITDB_ROOT_PASSWORD: gces
      MONGO_INITDB_DATABASE: parserdatabase

volumes:
  mongo-data:

networks:
  network-parser:
    driver: bridge
