name: CI Workflow

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build app
        run: |
          docker build -t gces-app .
      
      - name: Make autodoc
        run: |
          docker run gces-app sphinx-apidoc -o docs/rst ./src
          docker run gces-app make html -C docs/
      
      - name: Isort
        run: |
          pip install isort
          isort . 
      
      - name: Black
        run: |
          pip install black
          black .

      - name: Test, coverage
        run: |
          docker run gces-app pytest --cov
      
      - name: Install poetry and publish PyPI
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry python && \
          cd /usr/local/bin && \
          ln -s /opt/poetry/bin/poetry && \
          poetry config virtualenvs.create false && \
          poetry config pypi-token.pypi ${{ secrets.PYPI_KEY }}
          poetry build
          poetry publish
