name: CI Workflow

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  tests and coverage:
    name: Generate doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          with:
            fetch-depth: 0
      - name: Test, coverage and models ER
        run: |
          docker build -t gces-app .
          docker run gces-app pytest --cov tests
      
